RecipesProject/RecipesProject/Areas/Admin/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecipesProject.Areas.Admin.Models;
using RecipesProject.Data;
using RecipesProject.Data.Entities;
using RecipesProject.Models;
using RecipesProject.Models.RecipeViewModels;

namespace RecipesProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RecipesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RecipesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Recipes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Recipes
                .Where(r => r.IsApproved == false)
                .Include(r => r.Category);
            return View("Index", await applicationDbContext.ToListAsync());
        }

        // GET: Admin/Recipes/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Recipes == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipes
                .Include(r => r.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // GET: Admin/Recipes/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var existingRecipe = await _context.Recipes
                .Include(c => c.Category)
                .Include(r => r.RecipeIngredients)
                    .ThenInclude(ri => ri.Ingredient)
                .FirstOrDefaultAsync(r => r.Id == id);

            if (existingRecipe == null)
            {
                return NotFound();
            }
            var editViewModel = new EditRecipeViewModel
            {
                Id = existingRecipe.Id,
                Title = existingRecipe.Title,
                Description = existingRecipe.Description,
                Instructions = existingRecipe.Instructions,
                PrepTime = existingRecipe.PrepTime,
                CookTime = existingRecipe.CookTime,
                TotalTime = existingRecipe.TotalTime,
                Servings = existingRecipe.Servings,
                Image = existingRecipe.Image,
                CategoryId = existingRecipe.CategoryId,
                CategoryName = existingRecipe?.Category?.Name,
                Ingredients = existingRecipe?.RecipeIngredients.Select((ri, index) => new IngredientViewModel
                {
                    Index = index,
                    Id = ri.Ingredient!.Id,
                    Name = ri.Ingredient.Name,
                    Quantity = ri.IngredientQuanitity,
                }).ToList()
            };

            var categories = await _context.Categories.Where(x => x.Name != editViewModel.CategoryName).Select(x => new CategoryViewModel
            {
                Id = x.Id,
                Name = x.Name,
            }).ToListAsync();
            editViewModel.Categories = categories;
            return View(editViewModel);
        }


        // POST: Admin/Recipes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] Guid id, EditRecipeViewModel model)
        {
            if (model == null)
            {
                return BadRequest(); 
            }

            if (ModelState.IsValid)
            {
                var existingRecipe = await _context.Recipes
                    .Include(r => r.RecipeIngredients)
                    .FirstOrDefaultAsync(r => r.Id == model.Id);

                if (existingRecipe == null)
                {
                    return NotFound();
                }

                existingRecipe.Title = model.Title;
                existingRecipe.Description = model.Description;
                existingRecipe.Instructions = model.Instructions;
                existingRecipe.PrepTime = model.PrepTime;
                existingRecipe.CookTime = model.CookTime;
                existingRecipe.TotalTime = model.TotalTime;
                existingRecipe.Servings = model.Servings;
                existingRecipe.Image = model.Image;
                existingRecipe.CategoryId = model.CategoryId;

                existingRecipe.RecipeIngredients.Clear();
                if (model.Ingredients != null)
                {
                    foreach (var ingredientViewModel in model.Ingredients)
                    {
                        if (ingredientViewModel == null)
                        {
                            continue; 
                        }

                        var ingredient = new Ingredient
                        {
                            Id = ingredientViewModel.Id,
                            Name = ingredientViewModel.Name
                        };

                        existingRecipe.RecipeIngredients.Add(new RecipeIngredients
                        {
                            RecipeId = existingRecipe.Id,
                            Ingredient = ingredient,
                            IngredientQuanitity = ingredientViewModel.Quantity
                        });
                    }
                }

                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            var categories = await _context.Categories
                .Where(x => x.Name != model.CategoryName)
                .Select(x => new CategoryViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                }).ToListAsync();

            model.Categories = categories;
            return View(model);
        }

        // GET: Admin/Recipes/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Recipes == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipes
                .Include(r => r.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }
        // POST: Admin/Recipes/DeleteConfirmed/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var recipe = await _context.Recipes.FindAsync(id);
            if (recipe == null)
            {
                return NotFound();
            }

            _context.Recipes.Remove(recipe);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ApproveRecipe(Guid id)
        {
            var recipe = await _context.Recipes.FindAsync(id);
            if (recipe != null)
            {
                recipe.IsApproved = true;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        private bool RecipeExists(Guid id)
        {
            return (_context.Recipes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

RecipesProject/RecipesProject/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using RecipesProject.Contracts;
using RecipesProject.Data.Entities;

namespace RecipesProject.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }
        [HttpGet]
        public async Task<IActionResult> AllCategories()
        {
            try
            {
                List<Category> categories = await categoryService.AllCategoryAsync();
                return View(categories);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public async Task<IActionResult> AllFromCategories(Guid categoryId)
        {
            try
            {
                List<Recipe> recipes = await categoryService.AllFromCategoriesAsync(categoryId);
                return View(recipes);
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

RecipesProject/RecipesProject/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RecipesProject.Contracts;
using RecipesProject.Data;
using RecipesProject.Data.Entities;
using RecipesProject.Models.RecipeViewModels;
using System.Security.Claims;

namespace RecipesProject.Controllers
{
    public class RecipeController : Controller
    {
        private readonly IRecipeService recipeService;
        private readonly ICategoryService categoryService;

        public RecipeController(IRecipeService recipeService, ICategoryService categoryService)
        {
            this.recipeService = recipeService;
            this.categoryService = categoryService;
        }

        [HttpGet]
        public async Task<IActionResult> AllRecipes()
        {
            try
            {
                List<RecipeViewModel> recipes = await recipeService.AllAsync();
                return View(recipes);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public async Task<IActionResult> AddRecipe()
        {
            try
            {
                var categories = await categoryService.AllCategoryAsync();
                ViewBag.CategoryId = new SelectList(categories, "Id", "Name");
                return View();
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddRecipe(AddRecipeViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                    await recipeService.AddRecipe(model, userId, User.IsInRole("Admin"));
                    return RedirectToAction("Index", "Home");
                }
                return RedirectToAction ("AllRecipes");
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetRecipeById(Guid id)
        {
            try
            {
                var recipe = await recipeService.GetRecipeByIdAsync(id);

                if (recipe == null)
                {
                    return NotFound();
                }

                return View(recipe);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public async Task<IActionResult> Filter(FilterViewModel model)
        {
            try
            {
                var recipes = await recipeService.FilterAsync(model);
                return View("AllRecipes", recipes);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public async Task<IActionResult> RemoveFilters(FilterViewModel model)
        {
            try
            {
                model.ServingsFilter = 0;
                model.IngredientFilter = "";
                model.TimeFilter = "";
                return RedirectToAction("AllRecipes");
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetUserRecipes()
        {
            try
            {
                string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var recipes = await recipeService.GetUserRecipes(userId);
                return View("UserRecipes", recipes);
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

RecipesProject/RecipesProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecipesProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecipesProject.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" />

</head>
<body>
    <header class="position-sticky top-0">
        <nav class="navbar navbar-expand-sm navbar-light bg-white navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid justify-content-center">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/navbarimage/carmie-s-kitchen-recipe-picture.webp" alt="RecipesProject Logo" class="img-fluid navbar-brand-img">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-pink fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-pink fw-bold" asp-area="" asp-controller="Recipe" asp-action="AllRecipes">Recipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-pink fw-bold" asp-area="" asp-controller="Category" asp-action="AllCategories">Category</a>
                        </li>
                         @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-pink fw-bold" asp-area="" asp-controller="Recipe" asp-action="AddRecipe">Add</a>
                            </li>
                        }
                        <li class="nav-item">
                            @if (User.Identity!.IsAuthenticated && (User.IsInRole("Admin")))
                            {
                                <a class="nav-link text-pink fw-bold" asp-area="Admin" asp-controller="Recipes" asp-action="Index">Admin</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (User.Identity!.IsAuthenticated && !User.IsInRole("Admin"))
                            {
                                <a class="nav-link text-pink fw-bold" asp-area="" asp-controller="Recipe" asp-action="GetUserRecipes">My recipes</a>
                            }
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
            <style>
                body {
                    background-color:;
                }
            </style>
        </main>
    </div>

    <footer class="border-top text-white p-3">
        <div class="container mt-2">
            <div class="row">
                <div class="col-sn-4 col-md-4 col-lg-4 col-xl-4">
                    <h4>Recipe Application</h4>
                </div>
                <div class="col-sn-4 col-md-4 col-lg-4 col-xl-4">
                    <h4>Contact us</h4>
                    <div class="mt-3 mb-2">
                        <span><i class="fa-brands fa-instagram fs-5"></i></span>
                        <span class="fs-6 mx-1">Instagram</span>
                    </div>
                    <div class="mb-2">
                        <span><i class="fa-brands fa-facebook fs-5"></i></span>
                        <span class="fs-6 mx-1">Facebook</span>
                    </div>
                    <div class="mb-2">
                        <span><i class="fa-brands fa-whatsapp fs-5"></i></span>
                        <span class="fs-6 mx-1">Whatsapp</span>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>